### ISSUE TITLE
Persistence Image Weight Parameter

### ISSUE THREAD

**Issue by JacobPfau** [MathieuCarriere/sklearn_tda#2]
Thanks for the incredibly useful library!

The vectorization functions have worked fine for me, except now when I try to modify the weight parameter. I created a function called linearWeight and fed it to persistence image, but got the following error message:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-2-9c4983426410> in linearWeight(***failed resolving arguments***)
     14 
     15 def linearWeight(x):
---> 16     if x[0]<=x[1]: return 1
     17     else: return x[1]/x[0]
     18 

UnboundLocalError: local variable 'x' referenced before assignment

Exception ignored in: 'wrapper.call_wei'
Traceback (most recent call last):
  File "<ipython-input-2-9c4983426410>", line 16, in linearWeight
UnboundLocalError: local variable 'x' referenced before assignment

I got a similar error message when I tried using arctan weights (as you did in your example code file).

BTW I'm not sure if I missed anything, but it seems to me that in the literature some of the vectorization functions expect (x,y) coordinates and other expect (x,t). It's not hard to look it up, but it might be helpful to specify in the description readme.

**Comment by MathieuCarriere** [comment]
Hi!

This is strange I have no error if I run the examples with your weight function. This is maybe due to the OS (I only tested the code in Ubuntu 16.04). What OS are you using? Also could you send me the code involving the persistence image that you are trying to run?

Thanks for the comment on the readme, I will look that up. By (x,t) do you mean the use of (x,y-x) coordinate instead of (x,y), or just a change in the name of the second variable?

**Comment by JacobPfau** [comment]
I'm using linux mint 19. Yes, I did mean (x,y-x) transform. Here's the code:


```
for i in range(len(pdZeros)):
    if len(pdZeros[i])>0:
        pdZeros[i] = np.array(tda.DiagramPreprocessor(use=True, scaler=tda.BirthPersistenceTransform()).fit_transform(pdZeros[i]))
    if len(pdOnes[i])>0:
        pdOnes[i] = np.array(tda.DiagramPreprocessor(use=True, scaler=tda.BirthPersistenceTransform()).fit_transform(pdOnes[i]))

def linearWeight(x):
    if x[0]<=x[1]: return 1
    else: return x[1]/x[0]
    
TV = tda.PersistenceImage(resolution=[4,4], weight=linearWeight)

topVecTexts = []
for i, pdZ in enumerate(pdZeros):
    if len(pdZ)>1 or len(pdOnes[i])>1:
        imageZero=imageOne=np.zeros(16)
        if len(pdZ)>1:
            imageZero = TV.fit_transform([pdZ[0:len(pdZ)-1]])[0]
        if len(pdOnes[i])>0:
            imageOne = TV.fit_transform([pdOnes[i][0:len(pdOnes[i])]])[0]
        topVecTexts.append(np.concatenate((imageZero,imageOne)))
        
        if len(pdZ)<=1 or len(pdOnes[i])<=1:
            print(i)
            
    else:
        print(i)
        indices[i]=-1
        
indices = list(filter(lambda x: x!=-1, indices))
```

Thanks for the help!

**Comment by MathieuCarriere** [comment]
Ok I also got the error on Linux Mint 19. 

It really looks like an OS problem because everything works fine on Ubuntu 16.04. I have to admit that I don't know what is happening, but here is a (weird) workaround: things work (at least for me) if you feed the PersistenceImage with a constant function that always returns the desired function:

def linearWeight():
    def lw(x):
        if x[0]<=x[1]: return 1
        else: return x[1]/x[0]
    return lw

TV = tda.PersistenceImage(resolution=[4,4], weight=linearWeight())

This is dirty, but this is the only thing I have for now. I will look at it more carefully. 
Thanks for your comment.
