### ISSUE TITLE
runtime error for persistence fisher kernel

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [MathieuCarriere/sklearn_tda#8]
Hi Mathieu,

when I compute persistence fisher kernel, I sometimes get a runtime error.

/home/cai.507/anaconda3/lib/python3.6/site-packages/sklearn_tda/metrics.py:225: RuntimeWarning: invalid value encountered in arccos
  Xfit[i,j] = np.arccos(np.dot(np.sqrt(vectori), np.sqrt(vectorj)))

And the resulting kernel will has NAN in some entries. I am thinking about replacing nan in persistence fisher kernel with some default value? Do you think it is a good idea?

Also, there are two parameters bandwidth and bandwidth_fisher, what are the reasonable search range for these two hyperparameters?

Thanks!
Chen

**Comment by MathieuCarriere** [comment]
Hi Chen,

Thanks for your message. 

It is weird indeed, the only reason I can think of is because there is a division by zero somewhere, so I tried to fix this by changing the code a little. Could you try again and tell me what happens? Also, check that the bandwidths you are using are not zero as well.

Anyway, I guess replacing NaNs with a single number is OK, also I don't know which value would be best to use. Concerning the bandwidths, a standard procedure is to range on a logarithmic scale, like ..., 10^-4, 10^-3, ..., 1, 10, 10^2, ...

Mathieu

**Comment by Chen-Cai-OSU** [comment]
Hi Mathieu,

Thanks for the reply. I justed the tried updated code again but the same runtime error still happens just often. I am still doing test on more dataset and will keep you updated.

**Comment by MathieuCarriere** [comment]
Alright, keep me posted. Also, if you want, you can send me pairs of persistence diagrams which raise an error, and I can take a look myself.

Mathieu

**Comment by Chen-Cai-OSU** [comment]
Hi Mathieu,
I think the problem is due to some numerical issue for np.arccos. 

In the last few lines of the metrics.py (Xfit[i, j] =np.arccos(np.dot(np.sqrt(vectori), np.sqrt(vectorj))))
It sometimes happens that the inner product can be more than 1 (in my case, it is usually something like 1.000000002), doing some rounding fixes the issue for me.

**Comment by MathieuCarriere** [comment]
Aaah I see, thanks for the update. I just updated the code so that values are rounded to 1.
Thank you so much!
Mathieu
